DROP TABLE IF EXISTS EMPLOYEES;

CREATE TABLE EMPLOYEES(
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    last_name VARCHAR(255) NOT NULL,
    phone_number VARCHAR(255) NOT NULL,
    department_name VARCHAR(255) NOT NULL
);